### ISSUE TITLE
How is the score calculated?

### ISSUE THREAD

**Issue by anthnyprschka** [GuillaumeLeclerc/number-parsing#2]
HI Guillaume, 
thanks for the interesting package! One question regarding calculation of the score of the different candidates though: is it correct that you are adding the length of the modified string to the score (https://github.com/GuillaumeLeclerc/number-parsing/blob/master/numberParsing.js#L67)? What is the rationale behind that?

**Comment by GuillaumeLeclerc** [comment]
Hello,

I'm not 100% sure since it was a long time ago but if my memory is correct is that I wanted to prioritize formats that match more of the input.

Example:

Let's say you have `120,234.25`, you would have two formats that parse this:
- One with `,` as thousands separator
- One with `,` as decimal separator

Obviously in this case it's better to parse it as `120234.25` rather than `120.234`.

Hope it helps
